import type { Cards } from "../types/game.ts";

export const cards: Cards = [
	{ id: "un_espasses", trucValue: 11, palo: "espasses" },
	{ id: "un_bastos", trucValue: 10, palo: "bastos" },
	{ id: "un_oros", trucValue: 5, palo: "oros" },
	{ id: "un_copes", trucValue: 5, palo: "copes" },
	{ id: "dos_espasses", trucValue: 6, palo: "espasses" },
	{ id: "dos_bastos", trucValue: 6, palo: "bastos" },
	{ id: "dos_oros", trucValue: 6, palo: "oros" },
	{ id: "dos_copes", trucValue: 6, palo: "copes" },
	{ id: "tres_espasses", trucValue: 7, palo: "espasses" },
	{ id: "tres_bastos", trucValue: 7, palo: "bastos" },
	{ id: "tres_oros", trucValue: 7, palo: "oros" },
	{ id: "tres_copes", trucValue: 7, palo: "copes" },
	{ id: "quatre_espasses", trucValue: 1, palo: "espasses" },
	{ id: "quatre_bastos", trucValue: 1, palo: "bastos" },
	{ id: "quatre_oros", trucValue: 1, palo: "oros" },
	{ id: "quatre_copes", trucValue: 1, palo: "copes" },
	{ id: "cinc_espasses", trucValue: 2, palo: "espasses" },
	{ id: "cinc_bastos", trucValue: 2, palo: "bastos" },
	{ id: "cinc_oros", trucValue: 2, palo: "oros" },
	{ id: "cinc_copes", trucValue: 2, palo: "copes" },
	{ id: "sis_espasses", trucValue: 3, palo: "espasses" },
	{ id: "sis_bastos", trucValue: 3, palo: "bastos" },
	{ id: "sis_oros", trucValue: 3, palo: "oros" },
	{ id: "sis_copes", trucValue: 3, palo: "copes" },
	{ id: "set_espasses", trucValue: 9, palo: "espasses" },
	{ id: "set_bastos", trucValue: 4, palo: "bastos" },
	{ id: "set_oros", trucValue: 8, palo: "oros" },
	{ id: "set_copes", trucValue: 4, palo: "copes" },
	{ id: "madona", trucValue: 12, palo: "comodin" },
	{ id: "amo", trucValue: 13, palo: "comodin" },
];
